### PR TITLE
SubIterator should inherit from AbstractIterator

### PR DESCRIPTION
**Pull request by ralphtheninja**
Closes https://github.com/Level/subleveldown/issues/23

### CODE REVIEW

**Comment by ralphtheninja** [comment]
@vweevers Any thoughts on using `util.inherits` vs the `inherits` module? (which `memdown` uses).

**Comment by mafintosh** [comment]
@ralphtheninja i think you wanna move the .next to ._next if going down the inheritance route

**Comment by ralphtheninja** [comment]
> @ralphtheninja i think you wanna move the .next to ._next if going down the inheritance route

Aye. Was thinking of doing this next (nu pun indended :smile: )

**Comment by ralphtheninja** [comment]
> We're using util.inherits in other modules too, right? We should also update those.

@vweevers Create an issue please!

**Comment by ralphtheninja** [comment]
Will rebase this once https://github.com/Level/subleveldown/pull/27 is merged.

**Pull request merged**
